[build]
  command = "npx pnpm install --shamefully-hoist && npx next build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://zcaabteyobabratetdsc.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjYWFidGV5b2JhYnJhdGV0ZHNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzE3MTYsImV4cCI6MjA1ODg0NzcxNn0.BobZBc2fQzqNDKmXkwqrUihmxtwzKOWbj07cdcVQOtk"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true 